use shazampoc;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS SONGS, HASHES;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE SONGS (
    ID_SONG 	 	INT(11) 	    NOT NULL AUTO_INCREMENT,
    TITLE 		 	VARCHAR(60)     NOT NULL,
    PRIMARY KEY (ID_SONG)
);

CREATE TABLE HASHES (
    HASH_		 	BIGINT 	    	UNSIGNED NOT NULL,
    SONG_ID			INT(11)			NOT NULL,
    PRIMARY KEY (HASH_, SONG_ID)
);

ALTER TABLE HASHES 
    ADD CONSTRAINT VALID 
    FOREIGN KEY (SONG_ID) 
    REFERENCES SONG (ID_SONG) ON DELETE CASCADE ON UPDATE CASCADE; 
    
SELECT * FROM SONGS;
SELECT * FROM HASHES;

SHOW databases