use shazampoc;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS SONG, ZONE;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE SONG (
    ID_SONG 	 	INT(11) 	    NOT NULL AUTO_INCREMENT,
    TITLE 		 	VARCHAR(60)     NOT NULL,
    PRIMARY KEY (ID_SONG)
);

CREATE TABLE ZONE (
    HASH_		 	INT(11) 	    NOT NULL,
    TIMESTAMP_ 	 	TIMESTAMP	    NOT NULL,
    SONG_ID			INT(11)			NOT NULL,
    PRIMARY KEY (HASH_, TIMESTAMP_)
);

ALTER TABLE ZONE 
    ADD CONSTRAINT VALID_SONG 
    FOREIGN KEY (SONG_ID) 
    REFERENCES SONG (ID_SONG) ON DELETE CASCADE ON UPDATE CASCADE; 
    
SELECT * FROM SONG;
SELECT * FROM ZONE;